G.UI.AppWebMVC/Models/ErrorViewModel.cs
namespace G.UI.AppWebMVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

G.UI.AppWebMVC/Controllers/HomeController.cs
using G.UI.AppWebMVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace G.UI.AppWebMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

G.UI.AppWebMVC/Controllers/PersonaGController.cs
using G.EntidadesNegocio.EN;
using G.LogicaNegocio.BL;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace G.UI.AppWebMVC.Controllers
{
    public class PersonaGController : Controller
    {
        // GET: PersonaGController
        public async Task<ActionResult> Index()
        {
            var roles = await PersonaGBL.GetAll();
            return View(roles);
        }

        // GET: PersonaG/Details/5
        public async Task<ActionResult> Details(int id)
        {
            var PersonaGDAL = await PersonaGBL.GetById(id);
            return View(PersonaGDAL);
        }

        // GET: PersonaG/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: PersonaG/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(PersonaEN pPersonaEN)
        {
            try
            {
                var result = await PersonaGBL.Create(pPersonaEN);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PersonaG/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var PersonaGDAL = await PersonaGBL.GetById(id);
            return View(PersonaGDAL);
        }

        // POST: PersonaG/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(PersonaEN pPersonaEN)
        {
            try
            {
                var result = await PersonaGBL.Update(pPersonaEN);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: PersonaG/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            
            return View();
        }

        // POST: PersonaG/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(PersonaEN personaEN)
        {
            try
            {
                var result = await PersonaGBL.Delete(personaEN);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

G.UI.AppWebMVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

G.UI.AppWebMVC/Views/PersonaG/Create.cshtml
@model G.EntidadesNegocio.EN.PersonaEN
@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>
<hr />
<div class="col-md-4">
    <form asp-action="Create">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="form-group">
            <label asp-for="NombreG" class="control-label"></label>
            <input asp-for="NombreG" class="form-control" />
            <span asp-validation-for="NombreG" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="ApellidoG" class="control-label"></label>
            <input asp-for="ApellidoG" class="form-control" />
            <span asp-validation-for="ApellidoG" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="FechaNacimientoG" class="control-label"></label>
            <input asp-for="FechaNacimientoG" type="date" class="form-control" />
            <span asp-validation-for="FechaNacimientoG" class="text-danger"></span>
        </div>
        <br />
        <div class="form-group">
            <label asp-for="SueldoG" class="control-label"></label>
            <input asp-for="SueldoG" class="form-control" />
            <span asp-validation-for="SueldoG" class="text-danger"></span>
        </div>
        <br />
        <div class="form group">
            <label asp-for="EstatusG" class="control-label"></label>
            <select asp-for="EstatusG" class="form-control">
                <option value="Online">Online</option>
                <option value="Out of line">Out of line</option>
            </select>
            <span asp-validation-for="EstatusG" class="text-danger"></span>
        </div>
        <div>
            <input type="submit" value="Create" class="btn btn-primary" /> |
        </div>
    </form>
</div>
<br />
<div class="form-group">
    
    
    <a asp-action="Index">Regresar a la Lista</a>
</div>

G.UI.AppWebMVC/Views/PersonaG/Delete.cshtml
@model G.EntidadesNegocio.EN.PersonaEN

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonaEN</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Id)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Id)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimientoG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimientoG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SueldoG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SueldoG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstatusG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstatusG)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

G.UI.AppWebMVC/Views/PersonaG/Details.cshtml
@model G.EntidadesNegocio.EN.PersonaEN

@{
    ViewData["Title"] = "Details";
}

<h1>Detalles Del Registro</h1>

<div>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NombreG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NombreG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ApellidoG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ApellidoG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FechaNacimientoG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FechaNacimientoG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SueldoG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SueldoG)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.EstatusG)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.EstatusG)
        </dd>
    </dl>
</div>
<div>
    @Html.ActionLink("Editar", "Edit", new { id = Model.Id }) |
    <a asp-action="Index">Regresar a la Lista</a>
</div>

G.UI.AppWebMVC/Views/PersonaG/Edit.cshtml
@model G.EntidadesNegocio.EN.PersonaEN

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>PersonaEN</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NombreG" class="control-label"></label>
                <input asp-for="NombreG" class="form-control" />
                <span asp-validation-for="NombreG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ApellidoG" class="control-label"></label>
                <input asp-for="ApellidoG" class="form-control" />
                <span asp-validation-for="ApellidoG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FechaNacimientoG" class="control-label"></label>
                <input asp-for="FechaNacimientoG" class="form-control" />
                <span asp-validation-for="FechaNacimientoG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SueldoG" class="control-label"></label>
                <input asp-for="SueldoG" class="form-control" />
                <span asp-validation-for="SueldoG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EstatusG" class="control-label"></label>
                <input asp-for="EstatusG" class="form-control" />
                <span asp-validation-for="EstatusG" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

G.UI.AppWebMVC/Views/PersonaG/Index.cshtml
@model IEnumerable<G.EntidadesNegocio.EN.PersonaEN>

@{
    ViewData["Title"] = "Index";
}

<h1>Mantenimieto Para PersonaG</h1>

<p>
    <a asp-action="Create" class="btn btn-primary">Crear Nueva Persona</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.NombreG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ApellidoG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.FechaNacimientoG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.SueldoG)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.EstatusG)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.NombreG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ApellidoG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FechaNacimientoG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.SueldoG)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstatusG)
            </td>
            <td>
                @Html.ActionLink("Editar", "Edit", new { id=item.Id }) |
                @Html.ActionLink("Detalles", "Details", new { id=item.Id }) |
                @Html.ActionLink("Eliminar", "Delete", new { id=item.Id })
            </td>
        </tr>
}
    </tbody>
</table>

G.UI.AppWebMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - G.UI.AppWebMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/G.UI.AppWebMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">G.UI.AppWebMVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="PersonaG" asp-action="Index">Persona</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - G.UI.AppWebMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>